server:
  port: 8080

spring:
#  profiles:
#    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/toy
    username: toyproject
    password: epzk3201!
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    properties:
#      hibernate:
#        show-sql: true
#        format_sql: true
#        ddl-auto: none

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: mapper/*.xml